In [1]:
import numpy as np

In [2]:
ar=np.array([1,2,3,45,12,45,23,78,95,25,100])

In [3]:
ar

array([  1,   2,   3,  45,  12,  45,  23,  78,  95,  25, 100])

In [5]:
np.sort(ar)

array([  1,   2,   3,  12,  23,  25,  45,  45,  78,  95, 100])

In [8]:
np.searchsorted(ar , 200)

11

In [10]:
ar1=np.array([0,0,12,0,45,78,25,0,0,0])

In [11]:
ar1

array([ 0,  0, 12,  0, 45, 78, 25,  0,  0,  0])

In [12]:
np.count_nonzero(ar1)

4

In [13]:
np.extract(ar1>4 ,ar1)

array([12, 45, 78, 25])

In [14]:
#Byte-swaping

In [15]:
ar

array([  1,   2,   3,  12,  23,  25,  45,  45,  78,  95, 100])

In [16]:
a=np.copy(ar)

In [18]:
b=ar.view()

In [19]:
a

array([  1,   2,   3,  12,  23,  25,  45,  45,  78,  95, 100])

In [20]:
b

array([  1,   2,   3,  12,  23,  25,  45,  45,  78,  95, 100])

In [21]:
b[0]=40

In [22]:
b

array([ 40,   2,   3,  12,  23,  25,  45,  45,  78,  95, 100])

In [23]:
a[0]=30

In [24]:
a

array([ 30,   2,   3,  12,  23,  25,  45,  45,  78,  95, 100])

In [25]:
import numpy.matlib as nm

In [26]:
nm.zeros(4)

matrix([[0., 0., 0., 0.]])

In [28]:
nm.ones((3,2))

matrix([[1., 1.],
        [1., 1.],
        [1., 1.]])